!pip install pandas

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("incidence_per_1000_pop_at_risk.csv")
df.head(50)

,Country,Year,No. of cases,WHO Region
0,Afghanistan,2018,29.01,Eastern Mediterranean
1,Algeria,2018,0.00,Africa
2,Angola,2018,228.91,Africa
3,Argentina,2018,0.00,Americas
4,Armenia,2018,0.00,Europe
5,Azerbaijan,2018,0.00,Europe
6,Bangladesh,2018,0.69,South-East Asia
7,Belize,2018,0.01,Americas
8,Benin,2018,386.18,Africa
9,Bhutan,2018,0.01,South-East Asia
10,Bolivia (Plurinational State of),2018,1.41,Americas
11,Botswana,2018,0.59,Africa
12,Brazil,2018,5.12,Americas
13,Burkina Faso,2018,398.73,Africa
14,Burundi,2018,250.27,Africa
15,Cabo Verde,2018,0.01,Africa
16,Cambodia,2018,23.69,Western Pacific
17,Cameroon,2018,246.99,Africa
18,Central African Republic,2018,347.33,Africa
19,Chad,2018,164.83,Africa
20,China,2018,0.00,Western Pacific
21,Colombia,2018,8.50,Americas
22,Comoros,2018,18.76,Africa
23,Congo,2018,235.07,Americas
24,Costa Rica,2018,0.04,Americas
25,Côte d'Ivoire,2018,330.60,Africa
26,Democratic People's Republic of Korea,2018,0.36,Western Pacific
27,Democratic Republic of the Congo,2018,319.84,Africa
28,Djibouti,2018,35.21,Eastern Mediterranean
29,Dominican Republic,2018,0.12,Americas
30,Ecuador,2018,3.32,Americas
31,Egypt,2018,0.00,Eastern Mediterranean
32,El Salvador,2018,0.00,Americas
33,Equatorial Guinea,2018,269.01,Africa
34,Eritrea,2018,28.88,Africa
35,Eswatini,2018,0.84,Africa
36,Ethiopia,2018,31.81,Africa
37,Gabon,2018,248.23,Africa
38,Gambia,2018,66.00,Africa
39,Georgia,2018,0.00,Europe
40,Ghana,2018,224.34,Africa
41,Guatemala,2018,0.27,Americas
42,Guinea,2018,283.89,Africa
43,Guinea-Bissau,2018,123.31,Africa
44,Guyana,2018,44.37,Americas
45,Haiti,2018,1.61,Americas
46,Honduras,2018,0.13,Americas
47,India,2018,5.33,South-East Asia
48,Indonesia,2018,3.87,South-East Asia
49,Iran (Islamic Republic of),2018,0.00,Eastern Mediterranean

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2033 entries, 0 to 2032
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       2033 non-null   str
 1   Year          2033 non-null   int64
 2   No. of cases  2033 non-null   float64
 3   WHO Region    2033 non-null   str
dtypes: float64(1), int64(1), str(2)
memory usage: 63.7 KB

In [4]:
df.describe()

              Year  No. of cases
count  2033.000000   2033.000000
mean   2009.000000    109.187073
std       5.478573    157.896171
min    2000.000000      0.000000
25%    2004.000000      0.520000
50%    2009.000000     11.150000
75%    2014.000000    199.990000
max    2018.000000    743.510000

In [5]:
print(df.shape)

(2033, 4)